
package webService;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.naming.spi.ObjectFactory;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantService", targetNamespace = "http://webService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "AjouterEtud")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AjouterEtud", targetNamespace = "http://webService/", className = "webService.AjouterEtud")
    @ResponseWrapper(localName = "AjouterEtudResponse", targetNamespace = "http://webService/", className = "webService.AjouterEtudResponse")
    @Action(input = "http://webService/EtudiantService/AjouterEtudRequest", output = "http://webService/EtudiantService/AjouterEtudResponse")
    public boolean ajouterEtud(
        @WebParam(name = "arg0", targetNamespace = "")
        Etudiant arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNote", targetNamespace = "http://webService/", className = "webService.GetNote")
    @ResponseWrapper(localName = "getNoteResponse", targetNamespace = "http://webService/", className = "webService.GetNoteResponse")
    @Action(input = "http://webService/EtudiantService/getNoteRequest", output = "http://webService/EtudiantService/getNoteResponse")
    public double getNote(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<webService.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValidant", targetNamespace = "http://webService/", className = "webService.GetValidant")
    @ResponseWrapper(localName = "getValidantResponse", targetNamespace = "http://webService/", className = "webService.GetValidantResponse")
    @Action(input = "http://webService/EtudiantService/getValidantRequest", output = "http://webService/EtudiantService/getValidantResponse")
    public List<Etudiant> getValidant();

    /**
     * 
     * @return
     *     returns webService.Etudiant
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMajorant", targetNamespace = "http://webService/", className = "webService.GetMajorant")
    @ResponseWrapper(localName = "getMajorantResponse", targetNamespace = "http://webService/", className = "webService.GetMajorantResponse")
    @Action(input = "http://webService/EtudiantService/getMajorantRequest", output = "http://webService/EtudiantService/getMajorantResponse")
    public Etudiant getMajorant();

}
